-- MySQL Script generated by MySQL Workbench
-- jeu. 10 déc. 2020 01:34:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema footDb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema footDb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `footDb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `footDb` ;

-- -----------------------------------------------------
-- Table `footDb`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `footDb`.`article` (
  `id` INT NOT NULL,
  `title` MEDIUMTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `images` BLOB NULL DEFAULT NULL,
  `description` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `footDb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `footDb`.`product` (
  `id` INT NOT NULL,
  `nomproduit` MEDIUMTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `prix` DOUBLE NOT NULL,
  `image` BLOB NULL DEFAULT NULL,
  `descriptions` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `footDb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `footDb`.`users` (
  `id` BINARY(160) NOT NULL,
  `username` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `password` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `registered` DATETIME NULL DEFAULT NULL,
  `product_id` INT NOT NULL,
  `article_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_product_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_users_article1_idx` (`article_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_article1`
    FOREIGN KEY (`article_id`)
    REFERENCES `footDb`.`article` (`id`),
  CONSTRAINT `fk_users_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `footDb`.`product` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;

USE `footDb` ;

-- -----------------------------------------------------
-- procedure AdminAddorEdit
-- -----------------------------------------------------

DELIMITER $$
USE `footDb`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `AdminAddorEdit`(
IN _IdAdmin INT,
IN _Name varchar(45),
IN _CodeAdmin varchar(45),
IN _Salary int
)
BEGIN
	SELECT _IdAdmin AS 'idAdmin';
    
	IF _IdAdmin = 0 THEN
		INSERT INTO admin(Name,CodeAdmin,Salary)
        VALUES (_Name,_CodeAdmin,_Salary);
		COMMIT;
        SET _IdAdmin = LAST_INSERT_ID();
	ELSE 
		UPDATE admin
        SET
        Name = _Name,
        CodeAdmin = _CodeAdmin,
        Salary = _Salary
        WHERE IdAdmin = _IdAdmin;
	END IF;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure ClientAddorEdit
-- -----------------------------------------------------

DELIMITER $$
USE `footDb`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `ClientAddorEdit`(
IN _IdClient INT,
IN _NomClient varchar(45),
IN _PrenomClient varchar(45),
IN _Email varchar(45),
IN _TelephoneClient int,
IN _Password varchar(45)
)
BEGIN
	SELECT _IdClient AS 'idClient';
    
	IF _IdClient = 0 THEN
		INSERT INTO client(NomClient,PrenomClient,Email,TelephoneClient,Password)
        VALUES (_NomClient,_PrenomClient,_Email,_TelephoneClient,_Password);
		COMMIT;
        SET _IdClient = LAST_INSERT_ID();
	ELSE 
		UPDATE client
        SET
        NomClient = _NomClient,
        PrenomClient = _PrenomClient,
        Email = _Email,
        TelephoneClient = _TelephoneClient,
        Password = _Password
        WHERE IdClient = _IdClient;
	END IF;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
